# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np
import pandas as pd

In [5]:
arr = np.random.randint(1,21, (5,5))
arr[:, 2] = 1
arr

array([[11,  4,  1, 12,  8],
       [18, 20,  1, 18, 11],
       [14,  1,  1,  7, 13],
       [ 8, 17,  1, 13,  9],
       [16, 15,  1,  2, 18]], dtype=int32)

In [6]:
arr = np.random.randint(1,17, (4,4))
for i in range(len(arr[0])):
    arr[i][i] = 0
arr

array([[ 0,  2, 16, 10],
       [16,  0,  1,  7],
       [13,  9,  0,  7],
       [ 6, 13,  5,  0]], dtype=int32)

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [7]:
arr = np.random.randint(1,37, (6,6))
arr[2:5, 1:5]

array([[26, 33, 35, 31],
       [ 8,  3,  2, 34],
       [16, 36, 32, 32]], dtype=int32)

In [11]:
arr = np.random.randint(1,37, (5,5))
print(arr[0, :], arr[4, :], arr[:, 0], arr[:, 4])

[17  9 15 13 20] [27 30 32 20  6] [17 20  3 14 27] [20 13 17  4  6]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [13]:
arr1 = np.random.randint(1, 100, size=(3,4))
arr2 = np.random.randint(1, 50, size=(3, 4))
print(arr1 + arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1 / arr2)

[[100  18  91   9]
 [ 42  52  62  67]
 [ 78  79  57  37]]
[[ 14   2  89  -3]
 [-20  28   6   7]
 [ 76  -5   9  27]]
[[2451   80   90   18]
 [ 341  480  952 1110]
 [  77 1554  792  160]]
[[ 1.3255814   1.25       90.          0.5       ]
 [ 0.35483871  3.33333333  1.21428571  1.23333333]
 [77.          0.88095238  1.375       6.4       ]]


In [15]:
arr = np.random.randint(1, 17, (4,4))
print(arr)
print(arr.sum(axis = 0))
print(arr.sum(axis = 1))

[[12  1 15  9]
 [ 7 11 11  5]
 [16 16  1  8]
 [16 15 11  7]]
[51 43 38 29]
[37 34 41 49]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [20]:
arr = np.random.randint(1,100, (5,5))
print(arr.mean(), arr.std(), arr.var())

36.76 25.69401486727989 660.1824


In [21]:
arr = np.random.randint(1,10, (3,3))
print((arr - arr.mean()) / arr.std())

[[ 0.58299883  1.05999788  1.05999788]
 [ 0.58299883 -1.32499735  0.10599979]
 [-0.8479983   0.58299883 -1.8019964 ]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [24]:
arr = np.random.randint(1, 100, (3,3))
arr1 = np.arange(1,4)
print(arr)
print(arr1)
print(arr + arr1)


[[85 77 44]
 [95 22 85]
 [ 7 92 62]]
[1 2 3]
[[86 79 47]
 [96 24 88]
 [ 8 94 65]]


In [25]:
arr = np.random.randint(1, 100, (4, 4))
arr1 = np.arange(1,5)
print(arr)
print(arr1)
print(arr - arr1)


[[ 6 64 81 24]
 [36 56 42 62]
 [68 70 48 33]
 [ 9 43 16 10]]
[1 2 3 4]
[[ 5 62 78 20]
 [35 54 39 58]
 [67 68 45 29]
 [ 8 41 13  6]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [31]:
# arr = np.arange(1,10).reshape(3,3)
arr = np.random.randint(1, 20, (3,3))
print(arr)
print(np.linalg.det(arr))
print(np.linalg.inv(arr))
print(np.linalg.eig(arr))

[[ 6 19 17]
 [18  4  6]
 [ 2 17  7]]
2456.0
[[-0.03013029  0.06351792  0.01872964]
 [-0.04641694  0.00325733  0.10993485]
 [ 0.1213355  -0.02605863 -0.12947883]]
EigResult(eigenvalues=array([31.60742851+0.j        , -7.30371426+4.93548484j,
       -7.30371426-4.93548484j]), eigenvectors=array([[ 0.70493695+0.j        ,  0.07590495-0.3132414j ,
         0.07590495+0.3132414j ],
       [ 0.55547033+0.j        , -0.59492048+0.23904746j,
        -0.59492048-0.23904746j],
       [ 0.44104037+0.j        ,  0.69645115+0.j        ,
         0.69645115-0.j        ]]))


In [35]:
arr1 = np.random.randint(1, 20, (2,3))
arr2 = np.random.randint(1, 20, (3,2))
print(arr1)
print(arr2)
np.matmul(arr1, arr2)


[[12  8 13]
 [ 3 13 12]]
[[9 9]
 [2 2]
 [9 7]]


array([[241, 215],
       [161, 137]], dtype=int32)

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [36]:
arr = np.random.randint(1,10, (3,3))
print(arr.reshape(1,9))
print(arr.reshape(9,1))

[[8 1 2 4 3 5 4 5 5]]
[[8]
 [1]
 [2]
 [4]
 [3]
 [5]
 [4]
 [5]
 [5]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [47]:
arr = np.random.randint(1, 26, (5,5))
print(arr)
# corners = arr[1:3, :]
# to print the diagonal elements
# diagonal_elements = arr[[i for i in range(5)], [i for i in range(5)]]
corners = arr[[0,0, -1, -1], [0, -1, 0, -1]]
print(corners)

[[ 6  7 17 21  7]
 [16 11 13 15  5]
 [21 23  1  7 10]
 [15  2 23 20  1]
 [ 9  9 22  8 22]]
[ 6  7  9 22]


In [48]:
arr =  np.random.randint(1, 21, (4,4))
print(arr)
arr[arr > 10] = 10
print(arr)

[[ 3 13 16 15]
 [17 16  6 19]
 [ 6  7 10 13]
 [14  4 10  9]]
[[ 3 10 10 10]
 [10 10  6 10]
 [ 6  7 10 10]
 [10  4 10  9]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [60]:
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charles', 20, 65.2)], dtype= data_type)
print(data)

sort_arr = np.sort(data, order='age')
print(sort_arr)

[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charles', 20, 65.2)]
[('Charles', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [68]:
data_type = [('x', 'i4'), ('y', 'i4')]
arr = np.array([(1,3), (2,4), (4,6)])
print(arr)
for i in range(len(arr)-1):
    print(arr[i], arr[i+1])
    print(np.sqrt((arr[i+1][0] - arr[i][0])**2 +  (arr[i+1][1] - arr[i][1])**2))

[[1 3]
 [2 4]
 [4 6]]
[1 3] [2 4]
1.4142135623730951
[2 4] [4 6]
2.8284271247461903


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [70]:
arr = np.random.randint(1,16, (4,4))
arr[arr>10] = 0
print(arr)
print(arr.sum())

[[ 0  9  0  5]
 [ 1 10  5 10]
 [ 7  0  0  0]
 [ 3  1  9  0]]
60


In [72]:
import numpy.ma as ma
arr = np.random.randint(1,16, (4,4))
print(arr)
masked_arr = ma.masked_greater(arr, 10)
print(masked_arr)
print(masked_arr.sum())

[[14 10 12 14]
 [11 15 12 14]
 [ 3  4 12 10]
 [12  4  9  6]]
[[-- 10 -- --]
 [-- -- -- --]
 [3 4 -- 10]
 [-- 4 9 6]]
46


In [76]:
arr = np.random.randint(1,16, (3,3))
print(arr)
masked_arr = ma.masked_array(arr, mask= np.eye(3))
print(masked_arr)
mean_arr = masked_arr.mean()
print('mean : ',mean_arr)
print(masked_arr.filled(mean_arr))


[[ 4  2 13]
 [ 1 10  9]
 [11  3 11]]
[[-- 2 13]
 [1 -- 9]
 [11 3 --]]
mean :  6.5
[[ 6  2 13]
 [ 1  6  9]
 [11  3  6]]
